FROM node:25-alpine@sha256:bdf2cca6fe3dabd014ea60163eca3f0f7015fbd5c7ee1b0e9ccb4ced6eb02ef4

WORKDIR /usr/src/app

COPY package.json package-lock.json .npmrc ./

RUN npm install && \
    npm rebuild better-sqlite3 esbuild --ignore-scripts=false

COPY ./ ./

EXPOSE 80

CMD ["npm", "run", "dev"]
