FROM node:25-alpine@sha256:636c5bc8fa6a7a542bc99f25367777b0b3dd0db7d1ca3959d14137a1ac80bde2

WORKDIR /usr/src/app

COPY package.json package-lock.json ./

RUN npm install

COPY ./ ./

EXPOSE 80

CMD ["npm", "run", "dev"]
